"""3.

Revision ID: 1ed6ecf2f579
Revises: 72dda72d07e1
Create Date: 2021-12-30 15:07:59.356797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ed6ecf2f579'
down_revision = '72dda72d07e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customers', 'Gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('Gender', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
